config/routes.rb
Leather::Engine.routes.draw do
  get :ui_kit, to: "application#ui_kit", as: :ui_kit
  get :components, to: "application#components", as: :components
  get "/layouts/admin", to: "layouts#admin", as: :admin_layout
  get "/layouts/two_column", to: "layouts#two_column", as: :two_column_layout
  get "/layouts/three_column", to: "layouts#three_column", as: :three_column_layout
end

app/controllers/leather/application_controller.rb
module Leather
  class ApplicationController < ::ApplicationController
    layout 'application'

    def ui_kit
      set_tab :ui_kit
    end

    def components
      set_tab :components
    end
  end
end

app/controllers/leather/layouts_controller.rb
module Leather
  class LayoutsController < ApplicationController
    def admin
      set_tab :layouts
    end

    def two_column
      set_tab :layouts
    end

    def three_column
      set_tab :layouts
    end
  end
end

app/helpers/leather/application_helper.rb
module Leather
  module ApplicationHelper
    def method_missing method, *args, &block
      puts "LOOKING FOR ROUTES #{method}"
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/views/leather/application/_table.html.haml
%table{class: "table #{table_class}"}
  %thead
    %tr
      %th #
      %th First Name
      %th Last Name
      %th Username
  %tbody
    %tr
      %td 1
      %td Mark
      %td Otto
      %td @mdo
    %tr
      %td 2
      %td Jacob
      %td Thornton
      %td @fat
    %tr
      %td 3
      %td Larry
      %td the Bird
      %td @twitter

app/views/leather/application/components.html.haml
= content_for :extra_body_classes, "bg-gray-lighter container-lg"

.jumbotron.relative.no-margin.text-white{style: "height: 700px;"}
  .abs-cover.hero24
  .vertical-center.text-center
    .text-shadowed
      %h1.text-lighter Welcome to Leather
      %p.text-lighter Hello
    = link_to "Learn More", "", class: "btn btn-lg no-radius btn-primary"

%section.bg-gray-lightest.features
  .container
    .row
      .col-sm-4
        .feature
          %h4.detail-line Feature 1
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      .col-sm-4
        .feature
          %h4.detail-line Feature 2
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      .col-sm-4
        .feature
          %h4.detail-line Feature 3
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.

%section.bg-white.features
  .container
    .row
      .col-sm-3
        .feature
          %h4.detail-line Feature 1
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
      .col-sm-3
        .feature
          %h4.detail-line Feature 2
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
      .col-sm-3
        .feature
          %h4.detail-line Feature 3
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
      .col-sm-3
        .feature
          %h4.detail-line Feature 4
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.

%section.no-padding
  .flex-grid.text-center
    .flex-row
      = link_to "#", class: "feature-block feature-block-primary flex-cell" do
        %h4.text-light Hover Link Feature
        .detail-line
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      = link_to "#", class: "feature-block feature-block-primary flex-cell" do
        %h4.text-light Hover Link Feature
        .detail-line
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      = link_to "#", class: "feature-block feature-block-primary flex-cell" do
        %h4.text-light Hover Link Feature
        .detail-line
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.

%section.bg-gray-lightest.relative.image-block
  .image.image-right.col-sm-5.col-md-6
    .abs-cover.hero24
  .container
    .row
      .col-sm-7.col-md-5
        .image-block-copy
          %h2.no-margin.text-lighter Image Block Right
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
          = link_to "Learn More", "", class: "btn no-radius btn-primary"

%section.bg-gray-lightest.relative.image-block
  .image.image-left.col-sm-5.col-md-6
    .abs-cover.hero24
  .container
    .row
      .col-sm-7.col-md-5.col-md-offset-7.col-sm-offset-5
        .image-block-copy
          %h2.no-margin.text-lighter Image Block Left
          %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
          = link_to "Learn More", "", class: "btn no-radius btn-primary"

%section.bg-white
  .container
    .flex-grid.flex-grid-bordered.flex-grid-padded
      .flex-row
        .flex-cell.flex-cell-wide.bg-gray-lightest
          Flex Box
        .flex-cell 
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      .flex-row
        .flex-cell.bg-gray-lightest 
          Flex Box
        .flex-cell.flex-cell-wide
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      .flex-row
        .flex-cell.bg-gray-lightest
          Flex Box
        .flex-cell
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      .flex-row
        .flex-cell.bg-gray-lightest
          Flex Box
        .flex-cell
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
        .flex-cell
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
      .flex-row
        .flex-cell.bg-gray-lightest
          Flex Box
        .flex-cell
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
        .flex-cell
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
        .flex-cell
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.

%section.bg-gray-lightest
  .container
    .row
      .col-sm-2
        .text-center
          %p= image_tag "http://placehold.it/200x200", class: "img-responsive img-circle inline-block"
          %p
            %span.text-muted by
            Author Name
      .col-sm-9.col-sm-offset-1
        %h4.detail-line.text-lighter.text-muted.no-margin= Time.zone.now.strftime("%b %d, %Y")
        %h3.text-lighter.blog-heading Post Title

        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.

        %h4.blog-heading Subheading

        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.

        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.

%section.bg-gray-radial-light.no-overflow.image-block.image-block-bottom
  .container
    .row.relative
      .col-sm-6
        .image-block-copy.relative
          .vertical-center.absolute
            %h2.text-light.text-primary.no-margin Title
            %p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.
            = link_to "Learn More", "", class: "btn btn-primary no-radius btn-outline"
      .image.image-right.col-sm-6.col-md-4
        = image_tag "http://placehold.it/635x1034", class: "img-responsive"

%section.bg-white.text-center.cta.cta-inline
  .container
    %h2.text-primary.text-light.pull-left Call to Action
    = link_to "Learn More", "", class: "btn btn-primary btn-lg text-white no-radius btn-outline pull-right"

%section.bg-gray-radial-dark.text-white.no-overflow.image-block.image-block-bottom
  .container
    .row.relative
      .col-sm-6.col-sm-push-6
        .image-block-copy.relative
          .vertical-center.absolute
            %h2.text-light.no-margin Title
            %p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex. 
            = link_to "Learn More", "", class: "btn btn-default text-white no-radius btn-outline"
      .image.image-left.col-sm-6.col-md-4
        = image_tag "http://placehold.it/635x1034", class: "img-responsive"

%section.bg-white.text-center.cta
  .container
    %h2.text-primary.text-light Call to Action
    %p= link_to "Learn More", "", class: "btn btn-primary btn-lg text-white no-radius btn-outline"

app/views/leather/bootstrap_components/_dropdown_nav_item.html.haml
- id = Time.now.to_f
%li{ class: "#{active_class(href, options)} dropdown" }
  %a.dropdown-toggle{ id: id, href: href, data: { target: '#', toggle: 'dropdown'} }
    = text
    %b.caret
  %ul.dropdown-menu{ role: 'menu', aria: { labelledby: id } }
    = block

app/views/leather/bootstrap_components/_modal.html.haml
.modal.fade{ id: id }
  .modal-dialog
    .modal-content
      = block

app/views/leather/bootstrap_components/_modal_body.html.haml
.modal-body
  = block

app/views/leather/bootstrap_components/_modal_footer.html.haml
.modal-footer
  = block

app/views/leather/bootstrap_components/_modal_header.html.haml
.modal-header
  %button.close{ data: { dismiss: "modal" }, type: "button" }
    %span{ aria: { hidden: "true" } } ×
    %span.sr-only Close
  %h4.modal-title= title

app/views/leather/bootstrap_components/_nav_item.html.haml
%li{ class: active_class(href, options) }
  = link_to text, href, options

app/views/leather/bootstrap_components/_nav_list.html.haml
%ul.nav.navbar-nav{ html_options }
  = block

app/views/leather/bootstrap_components/_navbar.html.haml
- container_mode = html_options[:container_mode]
- html_options[:container_mode] = nil
- id = SecureRandom.hex(10)

- case container_mode
  - when :with
    %nav.navbar{ class: html_options[:class] }
      .container
        .navbar-header
          %button.navbar-toggle{ data: { toggle:'collapse', target:"#navbar-#{id}" }, type: 'button'}
            %span.sr-only
              Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to title, brand_link, :class => 'navbar-brand'
        .collapse.navbar-collapse{ id: "navbar-#{id}" }
          = block
  - when :fluid
    %nav.navbar{ class: html_options[:class] }
      .container-fluid
        .navbar-header
          %button.navbar-toggle{ data: { toggle:'collapse', target:"#navbar-#{id}" }, type: 'button'}
            %span.sr-only
              Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to title, brand_link, :class => 'navbar-brand'
        .collapse.navbar-collapse{ id: "navbar-#{id}" }
          = block
  - when :in
    .container
      .row.clearfix
        .column.col-md-12
          %nav.navbar{ class: html_options[:class] }
            .navbar-header
              %button.navbar-toggle{ data: { toggle:'collapse', target:"#navbar-#{id}" }, type: 'button'}
                %span.sr-only
                  Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              = link_to title, brand_link, :class => 'navbar-brand'
            .collapse.navbar-collapse{ id: "navbar-#{id}" }
              = block
  - else
    %nav.navbar{ class: html_options[:class] }
      .navbar-header
        %button.navbar-toggle{ data: { toggle:'collapse', target:"#navbar-#{id}" }, type: 'button'}
          %span.sr-only
            Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to title, brand_link, :class => 'navbar-brand'
      .collapse.navbar-collapse{ id: "navbar-#{id}" }
        = block

app/views/leather/layouts/_links.html.haml
.nav-menu-header
  = link_to "Leather", main_app.root_url, class: "nav-menu-brand"
%ul.nav.nav-menu-nav
  %li= link_to "UI Kit", ui_kit_url
  %li= link_to "Components", components_url
  %li{class: ("active" if current_page?(admin_layout_url))}= link_to "Admin Layout", admin_layout_url
  %li{class: ("active" if current_page?(two_column_layout_url))}= link_to "Two Column Layout", two_column_layout_url
  %li{class: ("active" if current_page?(three_column_layout_url))}= link_to "Three Column Layout", three_column_layout_url

app/views/leather/layouts/admin.html.haml
%nav.nav-menu.nav-menu-default.nav-menu-fixed-left.off-canvas.off-canvas-left-xs#target
  = render 'links'

#main
  .scroll-panel
    .scroll-panel-header
      = link_to "#", class: "btn btn-default btn-sm pull-left visible-xs", data: { toggle: "off-canvas", target: "#target" } do
        %i.fa.fa-bars
      = link_to "#", class: "btn btn-primary btn-sm pull-right" do
        %i.fa.fa-plus 
        New
      %h3.scroll-panel-title Title
    .scroll-panel-body
      %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

      %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

      %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

      %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

app/views/leather/layouts/three_column.html.haml
/ = navbar "Leather", page_path("home"), container_mode: :fluid, class: "navbar-default navbar-static-top no-margin" do
/   = nav_list do
/     = nav_item 'UI Kit', leather.ui_kit_path
/     = nav_item 'Components', leather.components_path
/     = dropdown_nav_item 'Layouts', '#' do
/       = nav_item 'Admin', leather.admin_layout_path
/       = nav_item 'Two Column', leather.two_column_layout_path
/       = nav_item 'Three Column', leather.three_column_layout_path
/   = nav_list class: 'navbar-right' do
/     - if user_signed_in?
/       = nav_item 'Sign Out', destroy_user_session_path, method: :delete
/     - else
/       = nav_item 'Sign In', new_user_session_path
/       = nav_item 'Sign Up', new_user_registration_path

%nav.nav-menu.nav-menu-default.nav-menu-fixed-left.off-canvas.off-canvas-left-sm#target
  = render 'links'

#main
  #left.full-width-xs
    .scroll-panel
      .scroll-panel-header.visible-xs.visible-sm
        = link_to "#", class: "btn btn-default btn-sm pull-left", data: { toggle: "off-canvas", target: "#target" } do
          %i.fa.fa-bars
        = link_to "#", class: "btn btn-primary btn-sm pull-right", data: { toggle: "columns" } do
          %i.fa.fa-plus
          New
        %h3.scroll-panel-title Title
      .scroll-panel-body
        .list-group
          - 10.times do
            = link_to "List Group Item", "#", class: "list-group-item", data: { toggle: "columns" }

  #right.hidden-xs.full-width-xs
    .scroll-panel
      .scroll-panel-header.visible-xs.visible-sm
        = link_to "#", class: "btn btn-default btn-sm pull-left visible-xs", data: { toggle: "columns" } do
          %i.fa.fa-chevron-left
        %h3.scroll-panel-title Title
      .scroll-panel-body
        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

app/views/leather/layouts/two_column.html.haml
= content_for :extra_body_classes, "container-lg bg-gray-lighter"

%nav.nav-menu.nav-menu-default.nav-menu-fixed-left.off-canvas.off-canvas-left#target
  = render 'links'

#main.bg-white
  #left.full-width-xs
    .scroll-panel
      .scroll-panel-header
        = link_to "#", class: "btn btn-default btn-sm pull-left", data: { toggle: "off-canvas", target: "#target" } do
          %i.fa.fa-bars
        = link_to "#", class: "btn btn-primary btn-sm pull-right", data: { toggle: "columns" } do
          %i.fa.fa-plus
          New
        %h3.scroll-panel-title Title
      .scroll-panel-body
        .list-group
          - 10.times do
            = link_to "List Group Item", "#", class: "list-group-item", data: { toggle: "columns" }

  #right.hidden-xs.full-width-xs
    .scroll-panel
      .scroll-panel-header
        = link_to "#", class: "btn btn-default btn-sm pull-left visible-xs", data: { toggle: "columns" } do
          %i.fa.fa-chevron-left
        %h3.scroll-panel-title Title
      .scroll-panel-body
        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.

        %p Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.